apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: apps
spec:
  components:
    - name: apps
      type: kustomize
      properties:
        repoType: git
        url: https://github.com/wjunlove123/KubeVela-GitOps-Infra-Demo
        secretRef: git-secret
        pullInterval: 1m
        git:
          branch: main
        path: ./apps
        imageRepository:
          image: wanyulingyun/kubevela-gitops-demo
          secretRef: dockerhub-secret
          filterTags:
            pattern: "^main-[a-f0-9]+-(?P<ts>[0-9]+)"
            extract: "$ts"
          policy:
            numerical:
              order: asc
          commitMessage: "Image: {{range .Updated.Images}}{{println .}}{{end}}"
